### ISSUE TITLE
Lack of security check and wrong use of libpcap API

### ISSUE THREAD

**Issue by Zero0one1** [ephracis/pylibpcap#2]
I found an issue when reading source code 'pcap_interface.c'. 

This issue is caused by forgetting to check the return value of libpcap API 'pcap_activate'. 

According to libpcap document "If pcap_activate() fails, the pcap_t * is not closed and freed; it should be closed using pcap_close()."

So it's safer to check it, and use 'pcap_close()' if an error occurs.

https://github.com/ephracis/pylibpcap/blob/bcab6cd2b27eeae0be1b3899cc1edb7b1f487136/pcap_interface.c#L161-L163

**Comment by ephracis** [comment]
Hi,

Thank you for finding this issue.

This repository is just a fork from https://sourceforge.net/projects/pylibpcap/ so this fix should be submitted upstream. Their bug page (where you can submit bug reports) is located here: https://sourceforge.net/p/pylibpcap/bugs/

**Comment by Zero0one1** [comment]
Thank you for your remind. I will submit it upstream.
